### ISSUE TITLE
Play/Pause Mode

### ISSUE THREAD

**Issue by aggonzo326** [carlmats/AwkwardSilence#2]
I wouldn't make this an issue normally , but I'm having trouble finding any place on the internet that discusses the issue I'm having. The Mute/Unmute works perfectly, but I can't get the Play/Pause menu to work. When I select it, it shows up blank. Thanks for making this app, and hopefully this issue can be resolved.

**Comment by pmatsson** [comment]
Hi! It sounds like you have an older version of the program. Are you building from source?
If not you can download the latest version from here: https://dl.dropboxusercontent.com/u/77837079/awkward2.rar

**Comment by aggonzo326** [comment]
Thanks for the link!
